variables:
  #base identity variables
  PROJECT_NAME: "migsappsample"
  PROJECT_ID: "19235528"
  #versioning variable
  MAJOR_VER: "0"
  MINOR_VER: "0"
  VERSION_TAG: "${MAJOR_VER}.${MINOR_VER}"

stages:
  - build
  - test

include:
  - local: '/.gitlab-ci-build.yml'
