.deploy-template:
  stage: deploy
  variables:
    GCP_WORKER_SIZE: "1"
    GPC_WORKER_SIZE_MAX: "8"
    GCP_WORKER_CPU_UTIL: "0.6"
    LOCUST_MASTER_PORT: "8089"
  tags:
    - docker
  image: google/cloud-sdk:alpine
  when: manual
  before_script:
    #login to gcp project
    - echo "${GCP_SERVICE_ACCOUNT}" | tr -d '\r' > keyfile.json
    - gcloud auth activate-service-account --key-file=keyfile.json
    - gcloud config set project ${GCP_PROJECT_ID}
  script:
    #create master instance
    - echo "Creating Locust Master Instance.."
    - |
      gcloud compute instances \
      create ${GCP_INSTANCE_MASTER} \
      --source-instance-template=${GCP_TEMPLATE_MASTER}-${MAJOR_VER}-${MINOR_VER}-${CI_PIPELINE_IID} \
      --zone=${GCP_REGION_NAME}-a \
      --private-network-ip=${LOCUST_MASTER_IP}
    - sleep 20s
    #create worker instance & auto scaling
    - echo "Creating Locust Worker Instance.."
    - |
      gcloud compute instance-groups managed \
      create ${GCP_INSTANCE_WORKER} \
      --size=${GCP_WORKER_SIZE} \
      --template=${GCP_TEMPLATE_WORKER}-${MAJOR_VER}-${MINOR_VER}-${CI_PIPELINE_IID} \
      --region=${GCP_REGION_NAME}
    - |
      gcloud compute instance-groups managed \
      set-autoscaling ${GCP_INSTANCE_WORKER} \
      --min-num-replicas=0 \
      --max-num-replicas=${GPC_WORKER_SIZE_MAX} \
      --scale-based-on-cpu \
      --target-cpu-utilization=${GCP_WORKER_CPU_UTIL} \
      --region=${GCP_REGION_NAME}
    - LOCUST_EXTERNAL_IP=$(gcloud compute instances list --zones=asia-southeast2-a --filter="name=(locust-prod-master)" --format="table(EXTERNAL_IP)" | grep -v "EXTERNAL_IP")
    - echo "Locust Access URL http://${LOCUST_EXTERNAL_IP}:8089 for project ${PROJECT_NAME}" > URL-Access.txt
    - echo "Locust Access URL http://${LOCUST_EXTERNAL_IP}:8089 for project ${PROJECT_NAME}"
  after_script:
    - rm keyfile.json
  artifacts:
    name: "Locust_URL_Access_id${PROJECT_ID}_${MAJOR_VER}-${MINOR_VER}-${CI_PIPELINE_IID}"
    paths: 
      - URL-Access.txt
    when: always
    expire_in: 3 hour

deploy-locust-develop:
  extends: .deploy-template
  environment:
    name: development
  variables:
    GCP_INSTANCE_MASTER: "locust-dev-master-id${PROJECT_ID}"
    GCP_TEMPLATE_MASTER: "locust-dev-master-template-id${PROJECT_ID}"
    GCP_INSTANCE_WORKER: "locust-dev-worker-group-id${PROJECT_ID}"
    GCP_TEMPLATE_WORKER: "locust-dev-worker-template-id${PROJECT_ID}"
  only:
    refs:
      - develop

deploy-locust-release:
  extends: .deploy-template
  environment:
    name: release
  variables:
    GCP_INSTANCE_MASTER: "locust-prod-master-id${PROJECT_ID}"
    GCP_TEMPLATE_MASTER: "locust-prod-master-template-id${PROJECT_ID}"
    GCP_INSTANCE_WORKER: "locust-prod-worker-group-id${PROJECT_ID}"
    GCP_TEMPLATE_WORKER: "locust-prod-worker-template-id${PROJECT_ID}"
  only:
    refs:
      - master