variables:
  #base identity variables
  PROJECT_NAME: "oriflamejump"
  PROJECT_ID: "1289"
  #versioning variable
  MAJOR_VER: "0"
  MINOR_VER: "0"
  VERSION_TAG: "${MAJOR_VER}.${MINOR_VER}"

stages:
  - build
  - pre-deploy
  - deploy

include:
  - local: '/.gitlab-ci-build.yml'
#  - local: '/.gitlab-ci-deploy.yml'
