.predeploy-template:
  stage: predeploy
  variables:
    GCP_TEMPLATE_SCOPES: "cloud-platform"
    GCP_LABEL_DIVDEPT: "personal"
    GCP_LABEL_QUEST: "locust"
  tags:
    - docker
  image: google/cloud-sdk:alpine
  before_script:
    #set env variable
    - IMAGE_NAME="locust"
    - BUILD_ENV_LOWERED="$(echo ${BUILD_ENV} | tr '[:upper:]' '[:lower:]')"
    - GCR_PATH="gcr.io/${GCP_PROJECT_ID}/${PROJECT_NAME}"
  script:
    #login to gcp project
    - echo "${GCP_SERVICE_ACCOUNT}" | tr -d '\r' > keyfile.json
    - gcloud auth activate-service-account --key-file=keyfile.json
    - gcloud config set project ${GCP_PROJECT_ID}
    #create instance template
    - |
      gcloud compute instance-templates \
      create-with-container ${GCP_TEMPLATE_NAME}-${MAJOR_VER}-${MINOR_VER}-${CI_PIPELINE_IID} \
      --container-image=${GCR_PATH}/${IMAGE_NAME}:${VERSION_TAG}.${CI_PIPELINE_IID} \
      --container-privileged ${GCP_DOCKER_ARGS} \
      --machine-type=${GCP_MACHINE_TYPE} \
      --boot-disk-size=${GCP_DISK_SIZE} \
      --scopes=${GCP_TEMPLATE_SCOPES} \
      --tags=${GCP_NETWORK_TAGS} \
      --labels=div-dept=${GCP_LABEL_DIVDEPT},quest=${GCP_LABEL_QUEST},environment=${BUILD_ENV_LOWERED},type=${GCP_LABEL_TYPE} \
      --preemptible
  after_script:
    - rm keyfile.json

predeploy-locust-master-develop:
  extends: .predeploy-template
  environment:
    name: development
  variables:
    BUILD_ENV: "Development"
    GCP_TEMPLATE_NAME: "locust-dev-master-template-id${PROJECT_ID}"
    GCP_MACHINE_TYPE: "n1-standard-1"
    GCP_DISK_SIZE: "10GB"
    GCP_LABEL_TYPE: "master"
    GCP_NETWORK_TAGS: "http-server,all-personal,locust-web"
    GCP_DOCKER_ARGS: "--container-arg='-f' --container-arg='/mnt/locust/locustfile.py' --container-arg='--master'"
  only:
    refs:
      - develop

predeploy-locust-worker-develop:
  extends: .predeploy-template
  environment:
    name: development
  variables:
    BUILD_ENV: "Development"
    GCP_TEMPLATE_NAME: "locust-dev-worker-template-id${PROJECT_ID}"
    GCP_MACHINE_TYPE: "n1-standard-2"
    GCP_DISK_SIZE: "10GB"
    GCP_LABEL_TYPE: "worker"
    GCP_NETWORK_TAGS: "http-server,all-personal"
    GCP_DOCKER_ARGS: "--container-arg='-f' --container-arg='/mnt/locust/locustfile.py' --container-arg='--worker' --container-arg='--master-host=10.184.1.1'"
  only:
    refs:
      - develop

predeploy-locust-master-release:
  extends: .predeploy-template
  environment:
    name: release
  variables:
    BUILD_ENV: "Release"
    GCP_TEMPLATE_NAME: "locust-prod-master-template-id${PROJECT_ID}"
    GCP_MACHINE_TYPE: "n1-standard-1"
    GCP_DISK_SIZE: "10GB"
    GCP_LABEL_TYPE: "master"
    GCP_NETWORK_TAGS: "http-server,all-personal,locust-web"
    GCP_DOCKER_ARGS: "--container-arg='-f' --container-arg='/mnt/locust/locustfile.py' --container-arg='--master'"
  only:
    refs:
      - master

predeploy-locust-worker-release:
  extends: .predeploy-template
  environment:
    name: release
  variables:
    BUILD_ENV: "Release"
    GCP_TEMPLATE_NAME: "locust-prod-worker-template-id${PROJECT_ID}"
    GCP_MACHINE_TYPE: "n1-standard-2"
    GCP_DISK_SIZE: "10GB"
    GCP_LABEL_TYPE: "worker"
    GCP_NETWORK_TAGS: "http-server,all-personal"
    GCP_DOCKER_ARGS: "--container-arg='-f' --container-arg='/mnt/locust/locustfile.py' --container-arg='--worker' --container-arg='--master-host=10.184.1.1'"
  only:
    refs:
      - master